#!/bin/sh

git clone https://github.com/loiccoyle/walls temp_walls

README_HEADER="""# Personal wallpapers

> Disclaimer: I do not own any of these wallpapers.

# Gallery
"""
echo "$README_HEADER" > README.md
for wall_file in $(ls temp_walls); do
    img_url="https://github.com/loiccoyle/walls/blob/main/${wall_file}?raw=true"
    md_text="![${wall_file}](${img_url})"
    echo "$md_text" >> README.md
done

rm -rf temp_walls
