name: generate-readme
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Format README
        run: sh generate_readme
      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git diff-index --quiet HEAD || git commit -m "[Bot] Generate README.md"
          git push
